config/routes.rb
#Rails.application.routes.draw do
  #get 'sessions/new'
  #get 'sessions/create'
 # get 'sessions/destroy'
  #resources :users
  #get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 # root "home#index"

Rails.application.routes.draw do
  root 'home#cara'

  get "home/index"
  
#<get '*path' => redirect('/')>  
  get "sessions/perfil"
  resources :users

  resources :sessions, only: [ :new, :create, :destroy]
  
  get "signup", to: "users#new", as: "signup"
  get "login" ,to: 'sessions#new', as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
end
#end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
    validates :address, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  	def index
  		
  	end
  	def cara
  		
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_address(params[:address])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to action: "perfil", notice: "Logged in!"
    else
      flash.now[:alert] = "Correo o contraseña invalida"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

  def perfil
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json 
  def create
    @user = User.new(user_params)

    respond_to do |format|

      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:dni, :nombre, :apellido, :address, :password, :password_confirmation, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/cara.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Proyecto</title>

  <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Proyecto final</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <p class="nav-link " ><%= link_to "Regístrate", signup_path %></p>
          </li>
          <li class="nav-item">

            <p class="nav-link" ><%= link_to "Inicia sesión", login_path %></p>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">Conocimiento para todos </h1>
        <h2 class="masthead-subheading mb-0">al alcance de un click</h2>
        <a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">Publicar consulta</a>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>

  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; Derechos reservados  2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  

</body>

</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>


	<title></title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
		
		<% if current_user %>
		  Logged in as <%= current_user.address %>.
		  <%= link_to "Salir sesion", logout_path %>
		<% else %>
		  
		  <%= link_to "Regístrate", signup_path %> 
		  o
		  <%= link_to "Inicia sesión", login_path %>
		<% end %>

		<p id="notice"> <%= notice %></p>
		<h1>Registro</h1>
		<p>Lorem ipsum …</p>



	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<section class=" form-group col-md-4 mb-3 " style="padding-top: 50px;" >
  <div class="field">
  
     <%= form.text_field :dni,placeholder: 'DNI'  ,class: 'form-group form-control' %></p>
  </div>

  <div class="field">
    
    <%= form.text_field :nombre,placeholder: 'Nombre',class: 'form-group form-control' %>
  </div>

  <div class="field">
    
    <%= form.text_field :apellido,placeholder: 'Apellidos' ,class: 'form-group form-control' %>
  </div>

  <div class="field">
  
    <%= form.text_field :address,placeholder: 'Correo' ,class: 'form-group form-control' %>
  </div>

  <div class="field">
 
    <%= form.password_field :password, placeholder: 'Contraseña' ,class: 'form-group form-control' %>
  </div>

  <div class="field">
     
    <%= form.password_field :password_confirmation,placeholder: 'Confirmar password',class: 'form-group form-control' %>
  </div>

  <div class="field">
   
    <%= form.text_field :phone ,placeholder: 'Numero celular',class: 'form-group form-control' %>
  </div>

  <div class="actions"><br>
    <%= form.submit "Registrate" ,class: ' btn btn-primary btn-lg'%>
  </div>
 </section> 
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Dni</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.dni %></td>
        <td><%= user.nombre %></td>
        <td><%= user.apellido %></td>
        <td><%= user.address %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <!--bootstrap--> 
   
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        
<head>
    <title></title>
</head>
<body class="color">

<!--MENÚ-->
 
<!--FIN MENU-->

<!--FORMULARIO DE REGISTRO-->

<div class="container shadow-lg pt-5 mt- 5 mb-5 bg-white rounded" style="padding-top: 50px; ">
		

		<div class=" mr-4 rounded float-right " style=" ">
			<%= image_tag 'creausuario.png' %> 
		</div>
				

		<div  class=" pl-4 ml-4"  style=" " >

		<h1 class=" ">Crear cuenta</h1>

		<%= render 'form', user: @user %>

		<!--<%= link_to 'Back', users_path %>-->
		</div>
</div>
<!--FIN FORMULARIO-->

            

        



<%= yield %>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>



               

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>DNI:</strong>
  <%= @user.dni %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @user.apellido %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Numero Celular:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>